version: "3.9"
services:
  # rundeck:
  #   image: rundeck/rundeck:3.4.9
  #   container_name: bfs_rundeck
  #   restart: always
  #   volumes:
  #     - /tmp/rundeck/projects:/var/rundeck/projects
  #     - /tmp/rundeck/var:/var/lib/rundeck/var
  #     - /tmp/rundeck/logs:/var/lib/rundeck/logs
  #     - /tmp/rundeck/data:/var/lib/rundeck/data
  #     - /run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - RUNDECK_ADMIN_NAME=admin
  #     - RUNDECK_ADMIN_PASS=admin
  #     - RUNDECK_USER_NAME=user
  #     - RUNDECK_USER_PASS=user
  #     - RUNDECK_JVM_XMX=1024m
  #     - RUNDECK_JVM_XMS=256m
  #     - RUNDECK_JVM_XX_MAX_PERM_SIZE=256m
  #     - RUNDECK_LOGLEVEL_DEFAULT=INFO
  #     - RUNDECK_GRAILS_SERVER_URL=http://localhost:4440
  #     - FRAMEWORK_SERVER_NAME=localhost
  #     - FRAMEWORK_SERVER_HOSTNAME=localhost
  #     - FRAMEWORK_SERVER_PORT=4440
  #     - FRAMEWORK_SERVER_URL=http://localhost:4440
  #     - FRAMEWORK_SERVER_USERNAME=admin
  #     - FRAMEWORK_SERVER_PASSWORD=admin
  #   ports:
  #     - 4440:4440

  redis:
    image: redis:5.0
    container_name: redis_localhost
    ports:
      - "6379:6379"

  redis2:
    image: 'bitnami/redis:latest'
    container_name: redis_ms_account
    environment:
      - REDIS_PORT_NUMBER=13158
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "13158:13158"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.3
    container_name: zookeeper_localhost
    user: root
    volumes:
      - ./zookeeper/data:/var/lib/zookeeper/data
      - ./zookeeper/log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.2.3
    container_name: kafka_localhost
    user: root
    volumes:
      - ./kafka/data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_HEAP_OPTS: -Xmx512M -Xms512M
    ports:
      - "9092:9092"

  zookeeper-0:
    image: bitnami/zookeeper:3.5
    container_name: zookeeper
    ports:
      - "2182:2182"
      - "3888:3888"
    networks:
      - kafkanet
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=admin
      - ZOO_SERVER_PASSWORDS=password
      - ZOO_PORT_NUMBER=2182
    volumes:
      - ./zookeeper-0/data:/bitnami/zookeeper

  kafka-0:
    image: bitnami/kafka:2.8.1
    container_name: kafka-0
    expose:
      - 9092
      - 9093
      - 9094
    ports:
      - "29092:29092"
    networks:
      - kafkanet
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2182
      - KAFKA_CFG_BROKER_ID=0
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,SSL:SSL,SASL_SSL:SASL_SSL,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,SSL://:9093,SASL_SSL://:9094,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-0:9092,SSL://kafka-0:9093,SASL_SSL://kafka-0:9094,EXTERNAL://localhost:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SSL
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.keystore.jks
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=42ae178c3cb34bf88a0c73786735bced
      - KAFKA_CFG_SSL_KEY_PASSWORD=42ae178c3cb34bf88a0c73786735bced
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.truststore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=0111351f4c0d4ad3b3a928b437666e41
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=SCRAM-SHA-256
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=SCRAM-SHA-256
    volumes:
      - ./kafka-0/data:/bitnami/kafka
      - ./aiven/client.keystore-17882158962488103631.p12:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro
      - ./aiven/client.truststore-7455930212614730998.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro
      - ./kafka_jaas.conf:/opt/bitnami/kafka/config/kafka_jaas.conf:ro
      - ./client.properties:/opt/bitnami/kafka/config/client.properties:ro
      - ./command.properties:/opt/bitnami/kafka/config/command.properties:ro
    depends_on:
      - zookeeper-0

  mongo:
    image: mongo
    container_name: mongo_localhost
    volumes:
      - ./mongo/db:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"
      ALLOW_EMPTY_PASSWORD: "yes"

  # mongo1:
  #   container_name: mongo1
  #   image: mongo:4.4
  #   volumes:
  #     - ~/mongors/data1:/data/db
  #     - ./rs-init.sh:/scripts/rs-init.sh
  #   networks:
  #     - mongors-network
  #   ports:
  #     - 27021:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: "root"
  #     MONGO_INITDB_ROOT_PASSWORD: "password"
  #   links:
  #     - mongo2
  #     - mongo3
  #   restart: always
  #   entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  # mongo2:
  #   container_name: mongo2
  #   image: mongo:4.4
  #   volumes:
  #     - ~/mongors/data2:/data/db
  #   networks:
  #     - mongors-network
  #   ports:
  #     - 27022:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: "root"
  #     MONGO_INITDB_ROOT_PASSWORD: "password"
  #   restart: always
  #   entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  # mongo3:
  #   container_name: mongo3
  #   image: mongo:4.4
  #   volumes:
  #     - ~/mongors/data3:/data/db
  #   networks:
  #     - mongors-network
  #   ports:
  #     - 27023:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: "root"
  #     MONGO_INITDB_ROOT_PASSWORD: "password"
  #   restart: always
  #   entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'k5451408_rahayu'
      MYSQL_USER: 'stationery'
      MYSQL_PASSWORD: 'stationery'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql/db:/var/lib/mysql

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loan_takeover_db
    volumes:
      - ./postgres/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  storage:
    container_name: fake-gcs-server
    image: fsouza/fake-gcs-server
    restart: always
    ports:
      - 8083:8083
    volumes:
      - ./fake-gcs/data:/data
    command: ["-scheme", "http", "-port", "8083", "-external-url", "http://[::]:8083"]
    networks:
      - storage-network

# volumes:
#   my-db:

networks:
  kafkanet:
    name: kafka-network
  # mongors-network:
  #   driver: bridge
  storage-network:
    driver: bridge